import { starterCells } from '../src/server/core/seed';
import { simulate } from '../src/server/sim/engine';
const cells = starterCells(1000000);
const deepest = cells.reduce((m, c) => Math.max(m, c.r), 0);
const res = simulate(cells, deepest);
const keys = Object.keys(res.contributions);
const pos = Object.entries(res.contributions).filter(([, v]) => v > 0);
console.log('total parts on machine:', cells.length);
console.log('distinct cells touched (events):', new Set(res.events.map((e) => e.cell)).size);
console.log('contribution keys:', keys.length, JSON.stringify(keys));
console.log("has empty-string key:", '' in res.contributions, 'value=', res.contributions['']);
console.log('carrying (state.ts formula) =', pos.length);
console.log('positive keys:', JSON.stringify(pos));
