import { starterCells } from '../src/server/core/seed';
import { simulate } from '../src/server/sim/engine';
const cells = starterCells(1000000);
const deepest = cells.reduce((m, c) => Math.max(m, c.r), 0);
const res = simulate(cells, deepest);
const kf = res.keyframes;
console.log('seed parts', cells.length);
console.log('reach', res.reach);
console.log('duration ms', kf[kf.length - 1]!.t);
console.log('keyframes', kf.length);
console.log('events', res.events.length);
